### ISSUE TITLE
Rename filenames

### ISSUE THREAD

**Issue by SoHotSoup** [Scramblelock/toronto-waste-lookup#3]
If your components are organized in directories would be better to have index.js file there than redundant `MyComponent/MyComponent.js`

e.g. if you rename `WasteCard/WasteCard.js` to `WasteCard/index.js` then you can just do this:
```
import WasteCard from './WasteCard';
```

instead:

```
import WasteCard from './WasteCard/WasteCard';
```

**Comment by Scramblelock** [comment]
Good idea!
